### ISSUE TITLE
.google_fit.token format

### ISSUE THREAD

**Issue by Terit** [IvanVojtko/googlefit-homeassistant#6]
When I run `python3 get_credentials.py` the resulting token is in some strange format that Home Assistant doesn't like.

```
<80>^D<95><80>^D^@^@^@^@^@^@<8c>^Ygoogle.oauth2.credentials<94><8c>^KCredentials<94><93><94>)<81><94>}<94>(<8c>^Etoken<94><8c>TOKEN REMOVED<94><8c>^Fexpiry<94><8c>^Hdatetime<94><8c>^Hdatetime<94><93><94>C
^Gæ^B^D^V^P^\^N9<87><94><85><94>R<94><8c>^Q_quota_project_id<94>N<8c>^G_scopes<94>]<94>
...
```

I'm assuming this should be a JSON string. @IvanVojtko  Can you point me in the right direction to generating a proper token?

**Comment by IvanVojtko** [comment]
@Terit hey. This is actually a correct format (I removed your token from comment so no one can use it). What's the issue you are having?

**Comment by Terit** [comment]
@IvanVojtko I had a previous version of this integration in place. I didn't read the error message well enough to realize I had a couple of extra keys in my config. 

Thanks for the help.

**Comment by tigattack** [comment]
FYI @Terit @IvanVojtko you can see edit history on issue comments. Best to delete the issue, since the token is still visible in the edit history.
